### ISSUE TITLE
Missing twist and wrench on endpoint_state topic

### ISSUE THREAD

**Issue by ghost** [RethinkRobotics/baxter_simulator#44]
When running baxter_gazebo, no matter what is happening at the endpoint, there is no twist or wrench on the `/robot/limb/left/endpoint_state` topic:

```
# after launching gazebo in another teriminal
# via $ roslaunch baxter_gazebo baxter_world.launch
$ rostopic echo /robot/limb/left/endpoint_state
```

yields

```
header: 
  seq: 307258
  stamp: 
    secs: 0
    nsecs: 0
  frame_id: ''
pose: 
  position: 
    x: 0.572575815071
    y: 0.181186651371
    z: 0.24619470767
  orientation: 
    x: 0.140772189718
    y: 0.989644952796
    z: 0.0116515084487
    w: 0.0255009874122
twist: 
  linear: 
    x: 0.0
    y: 0.0
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
wrench: 
  force: 
    x: 0.0
    y: 0.0
    z: 0.0
  torque: 
    x: 0.0
    y: 0.0
    z: 0.0

---
```

regardless of the force acting on the end effector. This is due to the fact that neither of these were ever implemented.
